#define SCATTERING_ORDERS 4

#define SCATTERING_RESOLUTION_HEIGHT 32
#define SCATTERING_RESOLUTION_VIEW 64
#define SCATTERING_RESOLUTION_SUN 32

#define SCATTERING_STEP_LENGTH 1000

#define SS_SETS_TRANSMITTANCE_SAMPLER 0
#define SS_SETS_SUM_IMAGE 1
#define SS_SETS_SCATTERING_IMAGE 2
#define SS_SETS_ENV 3
